baseURL = 'https://forestsonmiz.github.io/Vast-Infinity/'
locale = 'en-us'
title = 'The Worldbuilding and Stories of Vast Infinity'
theme = 'ananke'

defaultContentLanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
